Assets supports report
allegro/ralph pull request #2803
Opened 2016-09-13 07:46 UTC by mkurek

2016-09-13 11:24 UTC, ar4s commented
:ok:

2016-09-15 10:27 UTC, quamilek approved these changes
test

2016-09-15 10:28 UTC, quamilek requested changes
tests

2016-09-15 10:28 UTC, quamilek reviewed
test

2016-09-19 06:45 UTC, quamilek approved these changes

2016-09-19 09:54 UTC, xliiv commented on src/ralph/reports/views.py
> +        if model._meta.object_name == 'DataCenterAsset':
Perhaps, this could be model method removing this if.

2016-09-19 09:57 UTC, xliiv commented
:ok:

2016-09-19 10:01 UTC, merged