Add new settings ``RACK_LISTING_ORDER_REVERSE``
allegro/ralph pull request #2832
Opened 2016-10-05 12:44 UTC by ar4s

Set ``RACK_LISTING_ORDER_REVERSE = True`` for reverse number ordering in rack
visualization.

RACK_LISTING_ORDER_REVERSE = True   # 1..max_u_height from top to bottom
RACK_LISTING_ORDER_REVERSE = False  # max_u_height..1 from top to bottom

2016-10-05 12:45 UTC, ar4s commented
![image](https://cloud.githubusercontent.com/assets/351535/19113520/4d49d5d4-8b0a-11e6-9d23-afa334d64a03.png)

2016-10-05 13:42 UTC, mkurek commented on src/ralph/dc_view/templates/dc_view/settings_for_angular.js
> +{% cache 3600 settings_js %}
Do we have to cache it?

2016-10-05 13:47 UTC, ar4s commented on src/ralph/dc_view/templates/dc_view/settings_for_angular.js
> +{% cache 3600 settings_js %}
nope :)

2016-10-06 07:54 UTC, ghost approved these changes

2016-10-10 08:37 UTC, mkurek requested changes

2016-10-10 08:37 UTC, mkurek commented on src/ralph/settings/base.py
> +RACK_LISTING_REVERSE = True
default should be False. And consider changing name of this variable to better show numeration (from top to bottom or from bottom to top).

2016-10-10 11:38 UTC, ar4s commented on src/ralph/settings/base.py
> +RACK_LISTING_REVERSE = True
done

2016-10-10 13:06 UTC, mkurek approved these changes

2016-10-24 12:11 UTC, merged