[WIP] Add new transition actions: Assign new IP and Replace IP
allegro/ralph pull request #2845
Opened 2016-10-20 12:22 UTC by szok

2016-10-24 11:54 UTC, mkurek requested changes

2016-10-24 11:54 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +        kwargs['shared_params']['hostnames'][instances[0].pk] = new_hostname
`instances[0].pk` -> `instance.pk`

2016-10-24 11:54 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +        hostname = kwargs['shared_params']['hostnames'].get(instance.pk)
what if there is no `hostnames` in `kwargs['shared_params']`?

2016-10-24 11:54 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +            'field': ChoiceFieldWithOtherOption(
it should be basic choice field (we don't allow other value here - we should choose one of current IPs of this base object)

2016-10-24 11:54 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +            'field': ChoiceFieldWithOtherOption(
the same here - regular choice field instead of choice with other option

2016-10-25 07:12 UTC, mkurek requested changes

2016-10-25 07:12 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +    ip.address = str(network.get_first_free_ip())
some logging will be useful here (ex. 'Replacing <OLD-IP> to <NEW-IP> for <HOSTNAME>')

2016-10-25 07:56 UTC, mkurek requested changes

2016-10-25 07:56 UTC, mkurek commented on src/ralph/deployment/deployment.py
> +    for instance in objects:
one more thing - we should forbid running this action (Replace IP) with more than one object.

2016-10-25 09:05 UTC, szok commented on src/ralph/deployment/deployment.py
> +    for instance in objects:
Done

2016-10-25 10:03 UTC, mkurek approved these changes

2016-10-27 11:42 UTC, ghost approved these changes

2016-10-27 11:46 UTC, merged