Add link to service in CloudHost change view
allegro/ralph pull request #2896
Opened 2016-12-14 10:01 UTC by szok

2016-12-15 14:08 UTC, mkurek requested changes

2016-12-15 14:08 UTC, mkurek commented on src/ralph/virtual/admin.py
> +        return '<a href="{}">{}</a>'.format(
what if obj has no service_env?

2016-12-15 14:22 UTC, szok commented on src/ralph/virtual/admin.py
> +        return '<a href="{}">{}</a>'.format(
Done

2016-12-15 14:31 UTC, mkurek requested changes

2016-12-15 14:31 UTC, mkurek commented on src/ralph/virtual/admin.py
> +                    args=(obj.service_env.service.id,)
obj.service_env.service.id -> obj.service_env.service_id

2016-12-15 14:31 UTC, mkurek commented on src/ralph/virtual/admin.py
> +    get_service.admin_order_field = 'parent'
`parent`? why not `service_env`

2016-12-15 14:31 UTC, mkurek commented on src/ralph/virtual/admin.py
> +    get_service._permission_field = 'parent'
ditto

2016-12-15 15:10 UTC, szok commented on src/ralph/virtual/admin.py
> +    get_service.admin_order_field = 'parent'
done

2016-12-15 15:10 UTC, szok commented on src/ralph/virtual/admin.py
> +    get_service._permission_field = 'parent'
done

2016-12-15 15:12 UTC, szok commented on src/ralph/virtual/admin.py
> +                    args=(obj.service_env.service.id,)
done, but it is not necessary, because I have get str(obj.service_env.service) in line 320

2016-12-28 12:57 UTC, mkurek approved these changes

2016-12-28 12:58 UTC, merged