Add update position if chnage in parent
allegro/ralph pull request #2899
Opened 2016-12-15 11:07 UTC by szok

2016-12-15 12:15 UTC, ghost approved these changes

2016-12-15 14:13 UTC, mkurek requested changes

2016-12-15 14:13 UTC, mkurek commented on src/ralph/data_center/models/physical.py
> +                self._previous_state['rack_id'] != self.position
rack_id will be different than position, for sure :expressionless:

2016-12-15 14:13 UTC, mkurek commented on src/ralph/data_center/models/physical.py
> +                self._previous_state['rack_id'] != self.position
and i don't get this if - if current server is blade, then it's child - so `update_qs` should be empty (blade should have no children)

2016-12-15 14:23 UTC, szok commented on src/ralph/data_center/models/physical.py
> +                self._previous_state['rack_id'] != self.position
Done

2016-12-28 12:56 UTC, mkurek approved these changes

2016-12-28 12:57 UTC, merged