[WIP] Inheritance of custom fields
allegro/ralph pull request #2935
Opened 2017-01-12 13:54 UTC by mkurek

TODO:
- [ ] clean-up code
- [ ] comments about django workarounds
- [ ] tests

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +        RelatedManager = create_generic_related_manager_with_iheritance(
inheritance

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +    def prioretitize(self, model_or_instance):
prioritize

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +def create_generic_related_manager_with_iheritance(superclass):  # noqa: C901
inheritance

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +def _prioretitize_custom_field_values(objects, model, content_type):
prioritize

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +        self._prioretitize = True
prioritize

2017-01-14 13:08 UTC, vi4m commented on src/ralph/lib/custom_fields/fields.py
> +        if self._prioretitize:
prioritize

2017-01-16 09:31 UTC, ar4s requested changes

2017-01-16 09:31 UTC, ar4s commented on src/ralph/data_center/models/physical.py
> +    custom_fields_inheritance = [
@mkurek Can you write something about order of these values? Which value is on top of inheritance hierarchy?

2017-01-16 09:31 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +    ct_priority = {
maybe ``ct_priority = dict(enumerate(ct_priority))``?

2017-01-16 09:31 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +    result = []
you don't need this

2017-01-16 09:31 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +        result.append(cfv)
dd

2017-01-16 09:31 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +        custom_fields_values_ids.add(cfv.id)
dd

2017-01-16 09:31 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +    custom_fields_values_ids = set()
dd

2017-01-16 09:37 UTC, mkurek commented on src/ralph/lib/custom_fields/fields.py
> +    ct_priority = {
it will NOT work - notice that in index is enumerate is value of dict item, not key

2017-01-16 09:41 UTC, mkurek commented on src/ralph/data_center/models/physical.py
> +    custom_fields_inheritance = [
done (I've described it in CustomFieldsWithInheritanceRelation docstring)

2017-01-16 09:48 UTC, ar4s approved these changes

2017-01-16 09:48 UTC, ar4s commented on src/ralph/lib/custom_fields/fields.py
> +    For the example above the priority is as follows:
:+1:

2017-01-16 10:28 UTC, ar4s approved these changes

2017-01-17 08:42 UTC, szok approved these changes

2017-01-17 08:43 UTC, merged