Add hermes subscribers for Service
allegro/ralph pull request #2945
Opened 2017-01-20 10:22 UTC by szok

2017-01-20 10:34 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +    Update service owners
What's the point for such docstrings, if they're just a copy of funciton's name..? :wink:

2017-01-20 10:34 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +    Update service environments.
Improve docstring.

2017-01-20 10:34 UTC, xor-xor commented on src/ralph/assets/tests/test_subscribers.py
> +    def test_add_service(self):
What about using "given-when-then" naming scheme in test cases..?

2017-01-20 10:34 UTC, xor-xor commented on src/ralph/assets/apps.py
> +    def get_load_modules_when_ready(self):
I can hardly see a link between name of this function and its body :wink:

2017-01-20 10:34 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +def update_service_handler(data):
I'd use `data` name only as a last resort (i.e. when you **really** can't come up with anything more descriptive).

2017-01-20 10:41 UTC, szok commented on src/ralph/assets/apps.py
> +    def get_load_modules_when_ready(self):
https://github.com/allegro/ralph/blob/ng/src/ralph/apps.py#L18

2017-01-20 10:44 UTC, mkurek requested changes

2017-01-20 10:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +        get_user_model().objects.get_or_create(username=i['username'])[0]
i'd prefer to not use get_or_create here - just get

2017-01-20 10:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +        ServiceEnvironment.objects.get(
there should be check if there is no foreign key to this service env - if yes, then we shouldn't delete it but report an error

2017-01-20 10:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +        Service.objects.filter(uid=data['uid']).update(active=False)
check first if there is anything related to this service (for example any BaseObject) - if yes, then report an error and don't deactivate it

2017-01-20 10:44 UTC, mkurek commented on src/ralph/settings/test.py
> +HERMES_SERVICE_TOPICS = {
move it to base settings

2017-01-20 10:46 UTC, szok commented on src/ralph/settings/test.py
> +HERMES_SERVICE_TOPICS = {
it is in base settings, but returns "none", that only in production set topic

2017-01-20 11:18 UTC, xor-xor commented on src/ralph/assets/apps.py
> +    def get_load_modules_when_ready(self):
OK

2017-01-23 12:58 UTC, ghost approved these changes

2017-01-23 13:22 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +    current = set([u.id for u in service.environments.all()])
Minor nitpick - why `u` not `e` if you iterate over environments here..?

2017-01-23 13:22 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +                'Can not delete service environment because when assigned to objects.',  # noqa
`# noqa: E501`

2017-01-23 13:25 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +    Add, remove and update Service from hermes event.
Hmm... Looking at the decorators here, I see "create", "update" and "refresh" - I guess that "remove" is included in "refresh" then..? If so, then maybe add some explaination here..?

2017-01-23 13:28 UTC, xor-xor commented on src/ralph/assets/subscribers.py
> +            'Delete service `{}` with UID `{}`.'.format(
Or rather - "service with UID ... deleted"..?

2017-01-25 08:44 UTC, mkurek requested changes

2017-01-25 08:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +                'Can not delete service environment because when assigned to objects.',  # noqa: E501
`Can not delete service environment - it has assigned some base objects`

2017-01-25 08:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +                'Can not delete service because when assigned to objects.',
ditto

2017-01-25 08:44 UTC, mkurek requested changes

2017-01-25 08:44 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +        get_user_model().objects.get(username=i['username'])
what if user (username?) is not found?

2017-01-25 08:52 UTC, szok commented on src/ralph/assets/subscribers.py
> +        get_user_model().objects.get(username=i['username'])
Seriously?, previously I have get_or_create you wanted to change  to get() and I told you (face to face) about it that user will not exist.

Which version i have select?

2017-01-25 08:59 UTC, mkurek commented on src/ralph/assets/subscribers.py
> +        get_user_model().objects.get(username=i['username'])
The question we have to ask here if we want to have a service without proper owners or we don't want such situation.

Consider sth like: `business_owners = get_user_model().objects.filter(username__in=[i['username'] for i in business_owners])`

2017-01-25 09:20 UTC, szok commented on src/ralph/assets/subscribers.py
> +        get_user_model().objects.get(username=i['username'])
Done

2017-01-25 09:20 UTC, szok commented on src/ralph/assets/subscribers.py
> +                'Can not delete service environment because when assigned to objects.',  # noqa: E501
Done

2017-01-25 09:20 UTC, szok commented on src/ralph/assets/subscribers.py
> +                'Can not delete service because when assigned to objects.',
Done

2017-01-25 09:37 UTC, mkurek approved these changes

2017-01-26 07:17 UTC, merged