Display error message instead of throw 500
allegro/ralph pull request #2969
Opened 2017-02-27 13:21 UTC by ar4s

Changes:
 - added preview on graph's form,
 - added error message.

2017-02-27 13:30 UTC, mkurek approved these changes

2017-02-27 13:40 UTC, mkurek requested changes
menu not working

2017-03-01 11:02 UTC, mkurek approved these changes

2017-03-01 11:31 UTC, ghost approved these changes

2017-03-01 12:12 UTC, szok approved these changes

2017-03-01 12:20 UTC, merged