Allow filtering networks by member IP address
allegro/ralph pull request #2979
Opened 2017-03-15 15:01 UTC by romcheg

2017-03-15 16:16 UTC, mkurek requested changes

2017-03-15 16:16 UTC, mkurek commented on src/ralph/networks/filters.py
> +        for str_addr in filter_str.split(' '):
why do you replace all separators to spaces to then later split by space? couldn't you split by separators, using [re.split](https://docs.python.org/3/library/re.html#re.split) ?

2017-03-15 16:16 UTC, mkurek commented on src/ralph/networks/filters.py
> +                return queryset
you could add warning message in such case. See [here](https://github.com/allegro/ralph/blob/ng/src/ralph/admin/filters.py#L351) for example.

2017-03-15 16:51 UTC, romcheg commented on src/ralph/networks/filters.py
> +        for str_addr in filter_str.split(' '):
Done

2017-03-15 17:01 UTC, mkurek approved these changes

2017-03-15 17:03 UTC, romcheg commented
@mkurek some of the tests are still broken. I will resolve that as the first thing in the morning. Please don't merge yet :)

2017-03-16 13:15 UTC, mkurek commented
@romcheg could you make some test for ipv6 too?

2017-03-16 13:16 UTC, romcheg commented
@mkurek sure!

2017-03-22 08:48 UTC, ar4s approved these changes

2017-03-22 08:51 UTC, ghost approved these changes

2017-03-22 08:53 UTC, merged