Event processing for change management
allegro/ralph pull request #2998
Opened 2017-03-27 11:56 UTC by romcheg

This patch adds a generic subscriber for receiving and recording
change management events and a Jira processor for it. Base object
loading logic should be implemented for every secific case so it
is not included.

It also makes operations identifiable by their thicket_ids and extends
the list of possible operation statuses.

2017-03-28 06:19 UTC, mkurek requested changes

2017-03-28 06:19 UTC, mkurek commented on src/ralph/admin/apps.py
> +        from ralph.operations.changemanagement.subscribtions import receive_chm_event  # noqa
move this to `ralph.operation.apps`

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/jira.py
> +    return status_map[event_data['issue']['fields']['status']['name']]
what if we'll receive not-mapped status (afaik jira allows to create custom statuses)?

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/jira.py
> +    except TypeError:
weird, it looks like `KeyError` :)

2017-03-28 06:19 UTC, mkurek commented on src/ralph/settings/base.py
> +CHANGE_MGMT_BO_LOADER = os.getenv('CHANGE_MGMT_BO_LOADER', None)
i'd change `BO` to `BASE_OBJECT` - `BO` could be misleading here (someone could evaluate it to `BackOffice` for example)

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/subscribtions.py
> +        # TODO(romcheg): Change this for something sensible
👍

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/subscribtions.py
> +        user.is_active = False
couldn't you pass it to `get_or_create`? Sth like `user, created = model.objects.get_or_create(username=username, defaults={'is_active': False})`

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/subscribtions.py
> +        return
add some logging here (warning?)

2017-03-28 06:19 UTC, mkurek commented on src/ralph/operations/changemanagement/subscribtions.py
> +        change_processor = import_module(settings.CHANGE_MGMT_PROCESSOR)
you could import it in top-level imports, not only for this function

2017-03-28 08:03 UTC, romcheg commented on src/ralph/operations/changemanagement/subscribtions.py
> +        # TODO(romcheg): Change this for something sensible
Oh.. right...

2017-03-28 08:05 UTC, romcheg commented on src/ralph/operations/changemanagement/jira.py
> +    except TypeError:
This place has also caught me. However, if there is no assignee, event_data['issue']['fields']['assignee'] will be None. Applying [] operator to None produces a TypeError.

2017-03-28 08:09 UTC, mkurek commented on src/ralph/operations/changemanagement/jira.py
> +    except TypeError:
👍

2017-03-28 08:19 UTC, romcheg commented on src/ralph/admin/apps.py
> +        from ralph.operations.changemanagement.subscribtions import receive_chm_event  # noqa
Done

2017-03-28 08:21 UTC, romcheg commented on src/ralph/operations/changemanagement/jira.py
> +    return status_map[event_data['issue']['fields']['status']['name']]
I would suggest to act like in the case of an unknown operation type which is to log a warning and ignore the record. What do you think?

2017-03-28 08:21 UTC, mkurek commented on src/ralph/operations/changemanagement/jira.py
> +    return status_map[event_data['issue']['fields']['status']['name']]
👍

2017-03-28 08:22 UTC, romcheg commented on src/ralph/settings/base.py
> +CHANGE_MGMT_BO_LOADER = os.getenv('CHANGE_MGMT_BO_LOADER', None)
Done

2017-03-28 08:23 UTC, romcheg commented on src/ralph/operations/changemanagement/subscribtions.py
> +        user.is_active = False
Done

2017-03-28 10:49 UTC, romcheg commented on src/ralph/operations/changemanagement/subscribtions.py
> +        # TODO(romcheg): Change this for something sensible
Done

2017-03-28 10:52 UTC, romcheg commented on src/ralph/operations/changemanagement/subscribtions.py
> +        return
Done

2017-03-28 11:39 UTC, romcheg commented on src/ralph/operations/changemanagement/jira.py
> +    return status_map[event_data['issue']['fields']['status']['name']]
Done

2017-03-28 14:45 UTC, romcheg commented on src/ralph/operations/changemanagement/subscribtions.py
> +        change_processor = import_module(settings.CHANGE_MGMT_PROCESSOR)
Done

2017-03-29 07:22 UTC, mkurek approved these changes

2017-03-29 07:34 UTC, ar4s approved these changes

2017-03-30 06:19 UTC, szok commented on src/ralph/operations/changemanagement/subscribtions.py
> +    global base_object_loader
Why global ? ;(

2017-03-30 06:19 UTC, szok commented on src/ralph/operations/changemanagement/subscribtions.py
> +logger = logging.getLogger(__name__)
please move logger to top of file

2017-03-30 07:40 UTC, romcheg commented
@szok, thank you for those catches. Since they are not affecting the functionality of the code and we need this patch ASAP for testing purposes, I would propose to merge it as is. I will resolve your concerns in a separate patch.

2017-03-30 08:13 UTC, merged