Refactor operation status
allegro/ralph pull request #3014
Opened 2017-04-11 12:32 UTC by romcheg

List of possible operation statuses along with their meaning is
a flexible matter, especially in cases, when an external change
management software is used. Given that, having to rewrite and
release a new version of Ralph in order to adapt to the changes
is not a way to go.

This patch removes a hard-coded list of statuses from Ralph and
replaces it with a reference to a manageable entity called
OperationStatus. Those entities are manageable botj over the API
and the UI.

The change management listener's behavior was also set to create
new operation types in responce to incomming messages instead of
ignoring operations that have an unknown status.

2017-04-11 19:19 UTC, andrzej-jankowski commented on src/ralph/operations/api.py
> +    status = OperationStatusSerializer()
Maybe SlugRelatedField (http://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield) will be better here? You can define this field like that:
```
status = SlugRelatedField(
    many=False,
    read_only=False,
    slug_field='name',
    queryset= OperationStatus.objects.all()
)
```

Should work :)

2017-04-12 08:08 UTC, romcheg commented on src/ralph/operations/api.py
> +    status = OperationStatusSerializer()
That's an interesting option actually. However, I would like to discuss this topic a little in order to find the best solution. My concern is caused by the fact that now statuses are not hardcoded but stored in DB and allow dynamic management. Perhaps slugifying will bring more issues to API consumers than comfort. Say, someone wants to store an operation in an external data store and then use its status in order to find other operations. If the status is slugified, it won't be possible, if the name of the status was changed. So, I would vote for exposing statuses as structures. @mkurek, @vi4m, your opinions?

2017-04-13 07:31 UTC, andrzej-jankowski approved these changes

2017-04-13 08:17 UTC, mkurek requested changes

2017-04-13 08:17 UTC, mkurek commented on src/ralph/operations/filters.py
> +            status__id=int(self.value())
`status_id` (`status__id` will probably do join here)

2017-04-13 08:20 UTC, romcheg commented on src/ralph/operations/filters.py
> +            status__id=int(self.value())
Good catch. Thanks!

2017-04-13 08:29 UTC, mkurek approved these changes

2017-04-13 09:52 UTC, merged