Fetching available networks for cloud hosts
allegro/ralph pull request #3030
Opened 2017-04-20 13:05 UTC by romcheg

This patch allows to fetch available networks for cloud hosts
basing on the rack that contains the corresponding DC asset. It
also makes possible to fetch available networks for virtual servers
that are hosted by cloud hosts.

2017-04-21 05:19 UTC, andrzej-jankowski commented on src/ralph/virtual/tests/test_models.py
> +class CommonCodeMixin(object):
Maybe: VirtualAssetTestMixin?

2017-04-21 08:23 UTC, mkurek requested changes

2017-04-21 08:23 UTC, mkurek commented on src/ralph/virtual/models.py
> -            if isinstance(polymorphic_parent, DataCenterAsset):
`if isinstance(polymorphic_parent, (DataCenterAsset, CloudHost))`

2017-04-21 08:23 UTC, mkurek commented on src/ralph/virtual/tests/test_models.py
> +class CommonCodeMixin(object):
maybe `NetworkableBaseObjectTestMixin`?

2017-04-21 08:23 UTC, mkurek commented on src/ralph/virtual/models.py
> +        if isinstance(self.hypervisor, DataCenterAsset):
hypervisor has to be either DataCenterAsset or None, so simple check `if self.hypervisor` will be enough here

2017-04-25 12:36 UTC, romcheg commented on src/ralph/virtual/models.py
> -            if isinstance(polymorphic_parent, DataCenterAsset):
Done

2017-04-25 12:44 UTC, andrzej-jankowski approved these changes

2017-04-25 13:48 UTC, mkurek approved these changes

2017-04-26 07:41 UTC, merged