Filtering by configuration path and module for more objects
allegro/ralph pull request #3060
Opened 2017-05-09 12:50 UTC by romcheg

This patch adds ability to filter objects DataCenterAsset, DCHost,
VirtualServer or CloudHost types by their configuration_path.module
and configuration_path.path.

2017-05-09 12:55 UTC, ghost approved these changes

2017-05-10 07:06 UTC, mkurek requested changes

2017-05-10 07:06 UTC, mkurek commented on src/ralph/virtual/admin.py
> +    ):
hmm.. no :)

2017-05-10 07:57 UTC, romcheg commented on src/ralph/virtual/admin.py
> +    ):
That change was for sure made by evil hackers!

2017-05-10 08:46 UTC, mkurek approved these changes

2017-05-15 06:39 UTC, andrzej-jankowski approved these changes

2017-05-15 06:42 UTC, merged