Allow ordering DC assets by location
allegro/ralph pull request #3085
Opened 2017-06-02 08:33 UTC by romcheg

Since location is a complex field Ralph will order assets
by their datacenter, server room, rack, position and slot
in the specified order if those attributes are available.

2017-06-05 06:55 UTC, mkurek requested changes

2017-06-05 06:55 UTC, mkurek commented on src/ralph/data_center/admin.py
> +class DataCenterAssetChangeList(ChangeList):
use `RalphChangeList` (`ralph.admin.views.main.RalphChangeList`) here

2017-06-13 10:47 UTC, mkurek approved these changes

2017-06-14 10:08 UTC, ar4s approved these changes

2017-06-14 10:09 UTC, merged