Make rack attribute mandatory for DC assets
allegro/ralph pull request #3086
Opened 2017-06-02 10:57 UTC by romcheg

2017-06-05 06:46 UTC, mkurek requested changes

2017-06-05 06:46 UTC, mkurek commented on src/ralph/data_center/api/serializers.py
> +    rack = SimpleRackSerializer(required=True, allow_null=False)
since this is now serializer for read only, this won't be necessary

2017-06-13 10:56 UTC, mkurek approved these changes

2017-06-14 11:15 UTC, ar4s approved these changes

2017-06-14 11:16 UTC, merged