[WIP] Multi attachments
allegro/ralph pull request #3121
Opened 2017-07-20 15:41 UTC by ar4s

TODO:
- [ ] add test
- [ ] custom migration

2017-07-21 12:24 UTC, romcheg commented on src/ralph/lib/transitions/migrations/0006_auto_20170719_1209.py
> +                print('Attachment {} for transition history ({}) will be lost.'.format(attachment.file.url, th.transition_name))  # noqa
To be a good scout it's possible to zip/tar/winrar attachments, if there are more than one. However, I assume nobody's gonna use this rewind, so I'll live it up to your consideration :)

2017-07-21 12:25 UTC, romcheg commented on src/ralph/back_office/models.py
> +                    label=_('Report language (release)'),
Release raport language?

2017-07-21 12:25 UTC, romcheg commented on src/ralph/back_office/models.py
> +                    label=_('Report language (return)'),
ditto

2017-07-21 12:25 UTC, romcheg commented on src/ralph/back_office/models.py
> +                    label=_('Report language (loan)'),
ditto

2017-07-24 06:43 UTC, mkurek requested changes

2017-07-24 06:43 UTC, mkurek commented on src/ralph/admin/templatetags/ralph_tags.py
> +            'attachment_to_download', []
`attachments_to_download`?

2017-07-24 06:43 UTC, mkurek commented on src/ralph/lib/transitions/migrations/0006_auto_20170719_1209.py
> +    attachemnts = ZipFile(attachments_backup, 'w')
typo here

2017-07-24 11:57 UTC, mkurek approved these changes

2017-07-24 11:58 UTC, merged