Fix #3149
allegro/ralph pull request #3155
Opened 2017-09-01 19:49 UTC by ar4s

2017-09-01 19:56 UTC, vi4m requested changes

2017-09-01 19:56 UTC, vi4m commented on src/ralph/lib/metrics/collector.py
> +    STATSD_IS_INSTALLED = False
should be `True`

2017-09-02 08:55 UTC, vi4m commented on src/ralph/lib/metrics/collector.py
> +    def build_statsd_client(*args, **kwargs):
Why not have one function (`def build_statsd_client(*args, **kwargs)`:) with conditional statements inside? Creating alternative functions at runtime, inside the conditional smells like anti-pattern

2018-01-26 20:07 UTC, pnuckowski commented on src/ralph/lib/metrics/collector.py
> +        return StatsClient(
Why not to create custom "test" StatsClient?
```python
class TestStatsClient(StatsClient):
    def _after(self, data):
        pass
```

2019-02-19 19:40 UTC, vi4m commented
@ar4s it's taking too long to complete this. I'm closing this one.

2019-02-19 19:40 UTC, closed without merging