Refactor ``graph-query`` in dashboards
allegro/ralph pull request #3201
Opened 2017-12-20 13:53 UTC by ar4s

2017-12-21 09:53 UTC, mkurek submitted a review, later dismissed

2017-12-21 12:17 UTC, mkurek requested changes

2017-12-21 12:17 UTC, mkurek commented on src/ralph/dashboards/helpers.py
> +def normalize_value(model_class, labels, value, separator):
any description?

2017-12-21 12:17 UTC, mkurek commented on src/ralph/dashboards/helpers.py
> +        labels.split(separator)[0]
instead of passing here labels and separator just to split it here, maybe pass preprocessed value?

2017-12-21 12:17 UTC, mkurek commented on src/ralph/dashboards/models.py
> +            queryset = queryset.distinct().filter(**{filter_key: values})
are you sure that using distinct here (every time) is necessary?

2017-12-21 12:17 UTC, mkurek commented on src/ralph/dashboards/models.py
> +            # value = self.normalize_changelist_value(value)
is it necessary?

2017-12-21 13:52 UTC, ar4s commented on src/ralph/dashboards/models.py
> +            queryset = queryset.distinct().filter(**{filter_key: values})
is necessary

2018-01-02 14:50 UTC, mkurek approved these changes

2018-01-02 16:03 UTC, merged