Add cleanup security scans
allegro/ralph pull request #3282
Opened 2018-07-09 14:13 UTC by m1kra

RAS-1215

2018-07-09 16:09 UTC, mkurek commented on src/ralph/virtual/models.py
> +    def cleanup_security_scans(cls, instances, **kwargs):
the same method is defined already for `DataCenterAsset`. Please extract it to some common class or put somewhere as plain function - `transition_action` has additional argument - `models` - see https://github.com/allegro/ralph/blob/ng/src/ralph/deployment/deployment.py for examples.

2018-07-10 12:38 UTC, vi4m commented
@m1kra description is required for all pull requests (can re-paste from RAS-1215)

2018-07-10 16:54 UTC, m1kra commented
@vi4m Thank you, I have added the description.

@mkurek I have moved `cleanup_security_scans` to a new file in security app and added config loading it in `AppConfig.ready()`, following the approach in the deployment module. 
I am not quite sure if security module is the best location for it, but I find this solution logical. I was also thinking of adding it to transition app or base assets, so the additional config wouldn't be necessary.

2018-07-11 05:42 UTC, mkurek submitted a review, later dismissed

2018-07-12 05:06 UTC, ar4s requested changes

2018-07-12 05:06 UTC, ar4s commented on src/ralph/security/apps.py
> +        security/transitions.py will be loaded alongside modules reurned by
reurned -> returned

2018-07-12 06:12 UTC, m1kra commented on src/ralph/security/apps.py
> +        security/transitions.py will be loaded alongside modules reurned by
Done.

2018-07-12 06:18 UTC, mkurek approved these changes

2018-07-16 05:55 UTC, ar4s approved these changes

2018-07-30 14:50 UTC, merged