Intellectual property
allegro/ralph pull request #3317
Opened 2018-10-02 08:17 UTC by smaciejs

2018-10-03 05:41 UTC, mkurek commented
@smaciejs could you first try to rename model `TradeMarksLinkedDomains` to `TradeMarksLinkedDomain`? Django should ask you if you renamed this model and should prepare proper migration automatically - https://github.com/allegro/ralph/blob/981875c8bf1c26710d5d72de97ef0af2a9215d02/src/ralph/trade_marks/models.py#L110

2018-10-03 12:42 UTC, smaciejs commented
@mkurek  ok, I'll chagne it

2018-10-04 11:42 UTC, mkurek commented
migration 0001 was already merged - we should not modify it - there should be 0002 migration which just rename the model (and maybe some fields)

2018-10-04 12:24 UTC, mkurek requested changes

2018-10-04 12:24 UTC, mkurek commented on src/ralph/trade_marks/migrations/0002_auto_20181004_1417.py
> +        migrations.CreateModel(
didn't django ask about renaming existing model? :) we should use `RenameModel` here (and `RenameField` below as well )

https://docs.djangoproject.com/en/1.8/ref/migration-operations/#renamemodel
https://docs.djangoproject.com/en/1.8/ref/migration-operations/#renamefield

2018-10-04 13:01 UTC, smaciejs commented on src/ralph/trade_marks/migrations/0002_auto_20181004_1417.py
> +        migrations.CreateModel(
It didn't ask me about it. I'll do this in a proper way

2018-10-05 11:37 UTC, mkurek commented
@smaciejs the tests are not passing - shouldn't you rename some fields as well?

2018-10-05 12:55 UTC, mkurek approved these changes

2018-10-09 05:55 UTC, MarekBleschke approved these changes

2018-10-26 11:42 UTC, merged