RAS-1296 - handle empty/incorrect payload from dnsaas
allegro/ralph pull request #3381
Opened 2019-01-17 09:35 UTC by mahomahomaho

2019-02-06 11:04 UTC, MarekBleschke requested changes

2019-02-06 11:04 UTC, MarekBleschke commented on src/ralph/dns/tests.py
> +        # req._messages = MagicMock()
Commented code.

2019-02-13 17:06 UTC, mahomahomaho commented on src/ralph/dns/tests.py
> +        # req._messages = MagicMock()
removed

2019-02-20 11:03 UTC, MarekBleschke approved these changes

2019-02-25 12:18 UTC, Blejwi approved these changes

2019-02-27 11:42 UTC, merged