SSL Certificates API
allegro/ralph pull request #3413
Opened 2019-02-17 22:02 UTC by vi4m

2019-02-18 12:43 UTC, Blejwi submitted a review, later dismissed

2019-02-18 13:21 UTC, MarekBleschke requested changes

2019-02-18 13:21 UTC, MarekBleschke commented on src/ralph/ssl_certificates/api.py
> +class SaveSSLCertificate(RalphAPISaveSerializer):
I think it's not used anywhere.

2019-02-19 12:51 UTC, vi4m commented
@MarekBleschke removed unneded class

2019-02-20 07:05 UTC, MarekBleschke approved these changes

2019-02-21 14:09 UTC, merged