Introducing Backoffice Accessories managment.
allegro/ralph pull request #3548
Opened 2020-07-21 11:50 UTC by lukaszkarykowski

2020-10-10 13:48 UTC, vi4m commented
How is this going ?

2020-10-14 09:44 UTC, lukaszkarykowski commented
Still in progress. I got less time than i expected to finish things - to do is check failed Travis logs and add accessories counting. Hope to do this in next month.

2021-02-22 09:50 UTC, szymi- requested changes

2021-02-22 09:50 UTC, szymi- commented on src/ralph/accessories/migrations/0001_initial.py
> +# -*- coding: utf-8 -*-
Please squash the migrations into one.

2021-02-22 10:21 UTC, szymi- requested changes

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +        help_text=_('Manufacturer of accessories')
Maybe "Accessory manufacturer"? It's a help text describing a single accessory.

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +        help_text=_('Type of accessories')
"Accessory type"

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +        help_text=_('Name of accessories')
"Accessory name"

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +        help_text=_('Owner of the accessories'),
"Accessory owner"

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +        help_text=_('Accessories status')
"Accessory status"

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +    accessories_type = models.CharField(
`accessory_type`

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +    accessories_name = models.CharField(
`accessory_name`

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +class Accessories(
We have a `DataCenterAsset` model, not `DataCenterAssets`. I would stick to singular form here to be consistent, so this would be `class Accessory`

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +class AccessoriesStatus(Choices):
Singular form here too.

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +class AccessoriesUser(models.Model):
Singular form - `AccerssoryUser`

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/models.py
> +    accessories = models.ForeignKey(Accessories)
`accessory`

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/admin.py
> +class AccessoriesUserView(RalphDetailViewAdmin):
Ditto

2021-02-22 10:21 UTC, szymi- commented on src/ralph/accessories/admin.py
> +class AccessoriesAdmin(TransitionAdminMixin, RalphAdmin):
Ditto

2021-02-22 11:47 UTC, szymi- approved these changes

2021-02-24 08:48 UTC, merged