Run tests with GitHub Workflows
allegro/ralph pull request #3562
Opened 2020-09-13 17:48 UTC by romcheg

The new workflow runs the following tests in parallel:
- Code style
- Missing migrations for MySQL and PostgreSQL
- Settings tests
- Python tests for Ralph and ralph_dhcp_agent on both MySQL
  and PostgreSQL

2020-09-13 17:51 UTC, romcheg commented
As you can see there's plenty of repetition in the workflow file. Unfortunately GitHub workflows explicitly does not support YAML anchors at this moment. As soon as it's supported, it will be possible to reduce the size of the workflow file significantly.

2020-09-13 17:55 UTC, romcheg commented
Another thing: GitHub runs workflows for pull requests if there's at least one workflow in the base branch. That's why it won't run anything for this PR. I have tested these changes in my own repo: https://github.com/romcheg/ralph/actions/runs/252639137

2020-09-24 09:49 UTC, MarekBleschke submitted a review, later dismissed

2020-09-28 07:55 UTC, szymi- requested changes

2020-09-28 07:55 UTC, szymi- commented on .github/workflows/main.yml
> +    runs-on: ubuntu-18.04
Why not Ubuntu 20.04?

2020-09-28 07:55 UTC, szymi- commented on .github/workflows/main.yml
> +    runs-on: ubuntu-18.04
Ditto

2020-09-28 07:55 UTC, szymi- commented on .github/workflows/main.yml
> +    runs-on: ubuntu-18.04
Ditto

2020-09-28 07:55 UTC, szymi- commented on .github/workflows/main.yml
> +    runs-on: ubuntu-18.04
Ditto

2020-09-28 07:57 UTC, szymi- commented
I am ready to approve - I just thought Ubuntu 20.04 will save us one extra change in the future.

2020-09-28 12:53 UTC, szymi- commented
Just to clarify my previous comment: I know we use Ubuntu 18.04 as Ralph's container. But the images specified in this change are something different - they are the environment in which the tests run. So when in the future Github drops support for Ubuntu 18 (regardless of the fact that we might still be using it then), the jobs will start to fail for a reason unrelated to the changes in code, which is always annoying.

2020-09-28 14:29 UTC, romcheg commented
@szymi- I chose 18.04 simply because it's the version marked as "latest" on githut runners. However, 20.04 is also available and you've made a good point about dropping the support. I try to drop-in replace 18.04 by 20.04 and will make changes, if required.

2020-10-02 16:25 UTC, romcheg commented
@szymi- I have updated ubuntu on runners to 20.04. You can see the test results here: https://github.com/romcheg/ralph/pull/3/checks?check_run_id=1199731071

2020-10-06 07:54 UTC, szymi- approved these changes

2020-10-28 08:47 UTC, romcheg commented
@MarekBleschke ;)

2020-10-30 07:45 UTC, MarekBleschke approved these changes

2020-10-30 07:47 UTC, MarekBleschke approved these changes

2020-10-30 07:48 UTC, merged