feat: added helm chart
allegro/ralph pull request #3652
Opened 2021-08-11 14:17 UTC by wid

sHello,

Please accept my contribution of a helm chart to deploy ralph on a kubernetes cluster.

Once you install the prerequisites (see README.md), it will start ralph along with nginx, mysql and redis with the helm install.

2021-09-30 07:34 UTC, vi4m requested changes

2021-09-30 07:34 UTC, vi4m commented on charts/ralph/values.yaml
> +    - host: ralph-demo.allegro.tech
Not sure about that. Why this particular domain?

2021-10-07 11:01 UTC, wid commented on charts/ralph/values.yaml
> +    - host: ralph-demo.allegro.tech
Well it's if you want to use it yourself.
You can put anything else there.

2021-10-15 06:57 UTC, vi4m commented
I'm thinking about moving this configuration to the "contrib" directory (which already has infrastructure things like `docker-compose`, `dhcp` etc). What do you think?

2021-10-15 10:34 UTC, romcheg commented
@wid thanks for the great chart!

I agree with @vi4m that this should perhaps be in the `contrib` catalogue.

At the same time I kindly ask to not merge it right now. I agreed with @szymi- to do a little of a follow-up changes on the top in order to make it a production-grade chart including automatic testing

2021-10-15 10:35 UTC, wid commented
Yes, you can do that.

Le ven. 15 oct. 2021 à 08:57, ✪ vi4m Marcin Kliks ***@***.***>
a écrit :

> I'm thinking about moving this configuration to the "contrib" directory
> (which has infrastructure things like docker-compose, dhcp etc). What do
> you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/allegro/ralph/pull/3652#issuecomment-944048175>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA43ZSSKDAQ6OAVA4LIWDLUG7GGDANCNFSM5B6T5DUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-19 12:58 UTC, stxm commented on charts/ralph/README.md
> +https://kubedb.com/docs/v2021.06.23/setup/install/community/
Using kubedb seems like a uncommon choice to me. Suggestion to use mysql and redis as subchart.

2021-10-20 06:40 UTC, wid commented
Yes, mysql seems a better choice, specially that latest version do not have
basic needed features in the latest versions.

Le mar. 19 oct. 2021 à 14:59, Stan M ***@***.***> a écrit :

> f5d8be0#r731838371
> <https://github.com/allegro/ralph/commit/f5d8be0242c13fce6374467427ce9c15b637346c#r731838371>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/allegro/ralph/pull/3652#issuecomment-946697181>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA43ZUCBCS2R6FT4BLS64LUHVTUDANCNFSM5B6T5DUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2024-08-23 09:53 UTC, closed without merging