ITS-361078 | Added new condition to buyout link.
allegro/ralph pull request #3724
Opened 2022-04-07 08:12 UTC by lukaszkarykowski

2022-04-07 08:43 UTC, szymi- submitted a review, later dismissed

2022-04-07 08:45 UTC, vi4m requested changes

2022-04-07 08:45 UTC, vi4m commented on src/ralph/accounts/admin.py
> +            or item.custom_fields_as_dict.Purpose == 'Veryfication'
Verification

2022-04-21 09:50 UTC, szymi- requested changes

2022-04-21 09:50 UTC, szymi- commented on src/ralph/accounts/admin.py
> +            or item.custom_fields_as_dict.Purpose == 'Test'
This is not going to work if no such custom field exists:

```>>> item.custom_fields_as_dict.Purpose
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'Purpose'```

2022-04-27 10:51 UTC, szymi- requested changes

2022-04-27 10:51 UTC, szymi- commented on src/ralph/accounts/admin.py
> +            else:
Remove else, move the whole block to the end of this method to avoid code duplication.

2022-04-27 10:51 UTC, szymi- commented on src/ralph/accounts/admin.py
> +            else:
Ditto - this can be simplified.

2024-08-23 09:53 UTC, closed without merging