ITS-368993 | Added new status to backoffice assets.
allegro/ralph pull request #3725
Opened 2022-04-07 08:24 UTC by lukaszkarykowski

2022-04-07 08:44 UTC, szymi- approved these changes, later dismissed

2022-04-21 09:42 UTC, szymi- requested changes

2022-04-21 09:42 UTC, szymi- commented on src/ralph/back_office/models.py
> +    installed = _("sent")
Keep the old status. Somebody may be using it. Add a new one instead.

2022-04-21 11:53 UTC, hipek8 submitted a review, later dismissed

2022-04-27 10:53 UTC, szymi- submitted a review, later dismissed

2022-11-08 09:46 UTC, awieckowski approved these changes

2022-11-08 09:49 UTC, pyrkamarcin approved these changes

2022-11-08 10:57 UTC, merged